branch-defaults:
  default:
    environment: dms-web-dev
    group_suffix: null
deploy:
  artifact: target/dms-web.jar
global:
  application_name: dms-web
  branch: null
  default_ec2_keyname: eb-cli-personal
  default_platform: Java 8
  default_region: us-east-1
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli-personal
  repository: null
  sc: null
  workspace_type: Application
