branch-defaults:
  default:
    environment: dms-web-dev
deploy:
    artifact: target/dms-web.jar    
global:
  application_name: dms-web
  branch: null
  default_ec2_keyname: aws-eb-local
  default_platform: Java 8
  default_region: us-west-2
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: null
  workspace_type: Application
