branch-defaults:
  default:
    environment: dms-web-dev
    group_suffix: null	
global:
  application_name: dms-web
  default_ec2_keyname: dms-eb-key
  default_platform: Java 8
  default_region: us-west-2
  profile: eb-cli
  sc: null
