branch-defaults:
  default:
<<<<<<< HEAD
    environment: dms-web-dev
deploy:
    artifact: target/dms-web.jar    
global:
  application_name: dms-web
  branch: null
  default_ec2_keyname: aws-eb-local
=======
    environment: null
    group_suffix: null
  master:
    environment: null
deploy:
  artifact: target/dms-web.jar
global:
  application_name: dms-web
  default_ec2_keyname: aws-eb
>>>>>>> bc851ccb22bc4d70cb18ece304936dda50a88624
  default_platform: Java 8
  default_region: us-west-2
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
<<<<<<< HEAD
  repository: null
  sc: null
  workspace_type: Application
=======
  sc: git
>>>>>>> bc851ccb22bc4d70cb18ece304936dda50a88624
