branch-defaults:
  default:
    environment: null
    group_suffix: null
  master:
    environment: dms-web-dev
deploy:
  artifact: target/dms-web.jar
global:
  application_name: dms-web
  default_ec2_keyname: aws-eb
  default_platform: Java 8
  default_region: us-west-2
  profile: eb-cli
  sc: git
