
INSERT INTO product_doc_conf (PR_DOC_CONF_ID,PRODUCT_ID,DOC_TYPE_CODE,DESCRIPTION,IS_MANDATORY,GROUP_ID,IS_MULTIPLE_ITEM_ALLOWED) VALUES (300004,10,'LEFTIMAGE','Vehicle Left side Image',true,0,false);
INSERT INTO product_doc_conf (PR_DOC_CONF_ID,PRODUCT_ID,DOC_TYPE_CODE,DESCRIPTION,IS_MANDATORY,GROUP_ID,IS_MULTIPLE_ITEM_ALLOWED) VALUES (300005,10,'FRONTIMAGE','Vehicle Front side Image',true,0,false);
INSERT INTO product_doc_conf (PR_DOC_CONF_ID,PRODUCT_ID,DOC_TYPE_CODE,DESCRIPTION,IS_MANDATORY,GROUP_ID,IS_MULTIPLE_ITEM_ALLOWED) VALUES (300006,10,'BACKIMAGE','Vehicle Back side Image',true,0,false);
INSERT INTO product_doc_conf (PR_DOC_CONF_ID,PRODUCT_ID,DOC_TYPE_CODE,DESCRIPTION,IS_MANDATORY,GROUP_ID,IS_MULTIPLE_ITEM_ALLOWED) VALUES (300007,10,'TOPIMAGE','Vehicle Top Image',true,0,false);